name: Build changelog

outputs:
  has-prs:
    value: ${{ steps.build-changelog.outputs.categorized_prs || steps.build-changelog.outputs.uncategorized_prs }}
  previous-version:
    value: ${{ steps.build-changelog.outputs.fromTag }}
  next-version:
    value: ${{ steps.next-version.outputs.version }}
  notes:
    value: ${{ steps.process-changelog.outputs.changelog }}
  release:
    value: ${{ steps.next-release.outputs.release }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5

    - run: pip install semver
      shell: bash

    - id: build-changelog
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        configuration: ${{ github.action_path }}/config.json
        outputFile: NEXT.md
        toTag: HEAD

    - id: process-changelog
      run: |
        echo 'changelog<<EOF' >> $GITHUB_OUTPUT
        cat NEXT.md | python ${{ github.action_path }}/process_changelog.py >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash

    - id: next-release
      run: |
        echo "release=$(cat NEXT.md | python ${{ github.action_path }}/next_release.py)" >> $GITHUB_OUTPUT
      shell: bash

    - id: next-version
      run: |
        echo "version=$(python ${{ github.action_path }}/next_version.py \
          ${{ steps.build-changelog.outputs.fromTag }} \
          ${{ steps.next-release.outputs.release }})" >> $GITHUB_OUTPUT
      shell: bash
